### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by notginned** [miffi/apropospriate.nvim#2]
I'll keep adding stuff as I find them

# Comments can be italicized
`Comment      { fg = base01, gui = 'italic' }, -- any comment`

# Different Folded highlight
The current folded highlight looks very similar to comments, so we could spice them up a bit, and maybe bold it too.
`Folded       { fg = purple, gui = 'bold' }, -- line used for closed folds`

**Comment by miffi** [comment]
I personally don't like italicized text in the terminal for anything. I'll leave it to the user to override the highlight if they want that.

> Different Folded highlight

I've changed the folded highlight to `indigo1` instead of the suggested `purple` because purple is already used in a lot of places

Let me know if you have any more suggestions.
